# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-11 23:33
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cradmin_javascript_demos', '0002_fictionalfigurecollection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fictionalfigurecollection',
            name='secondary_fictional_figure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cradmin_javascript_demos.FictionalFigure'),
        ),
    ]
