# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-13 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cradmin_javascript_demos', '0003_auto_20161212_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='fictionalfigure',
            name='is_godlike',
            field=models.BooleanField(default=False),
        ),
    ]
