from . import mixins  # noqa
from . import generic  # noqa
from . import formbase  # noqa
from . import crudbase  # noqa
from . import create  # noqa
from . import update  # noqa
from . import delete  # noqa
from . import detail  # noqa
from . import listbuilderview  # noqa
