# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-15 07:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cradmin_listbuilder_guide', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='artist_app',
            new_name='artist',
        ),
    ]
