# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-16 09:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cradmin_gettingstarted', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
