# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-16 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cradmin_gettingstarted', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountadministrator',
            old_name='administrator',
            new_name='user',
        ),
    ]
