# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-28 04:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cradmin_gettingstarted', '0002_auto_20170216_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('body', models.TextField(max_length=255)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('number_of_likes', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cradmin_gettingstarted.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.SlugField()),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='tags',
            field=models.ManyToManyField(to='cradmin_gettingstarted.Tag'),
        ),
    ]
