# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-28 13:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cradmin_gettingstarted', '0003_auto_20170228_0555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
